import { sampleAudio, sampleArtwork } from './mediaSamples.ts'
// Synthetic records only. Never imported by production data paths.
const now = new Date()
export const today = `${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`
const stamp = now.toISOString()
export const sampleMembers = [
  { id: 'dev-user', display_name: 'Dev Admin', email: 'preview@example.test', role: 'admin', position: 'Operations', department: 'Studio', bio: 'Production, scheduling, and team operations.', pronouns: 'they/them' },
  ...['Jamie Rivera', 'Alex Morgan', 'Riley Chen', 'Taylor Brooks'].map((display_name, index) => ({ id: `00000000-0000-4000-8000-00000000000${index+1}`, display_name, email: `member${index+1}@example.test`, role: 'member', position: ['Studio','Production','Marketing','Operations'][index], department: 'Studio', bio: null, pronouns: null })),
].map(member => ({...member, status:'active', avatar_url:null, banner_url:null, socials:{}, preferences:{}, created_at:stamp, managed_by:'dev-user'}))
export const sampleProjects = ['Echoes in Gold','After Hours EP','The Long Way Home'].map((title,index) => ({ id:`sample-project-${index}`, team_id:'sample-team', owner_id:'dev-user', title, name:title, objective:['Mix & master','Finish vocal edits','Prepare final delivery'][index], status:'active', target_date:today, created_at:stamp, updated_at:stamp, completed_at:null }))
export const sampleTasks = ['Review the latest mix','Prepare session files','Confirm the vocal session'].map((title,index) => ({ id:`sample-task-${index}`, title, description:null, category:'Production', sort_order:index, is_required:false, is_completed:false, completed_at:null, due_date:today, visible_on_overview:true, source_type:'custom', source_template_id:null, source_template_item_id:null, created_at:stamp, updated_at:stamp, scope:'member', assigned_to:'dev-user', assigned_to_name:'Dev Admin', can_complete:true, batch:null, project_id:sampleProjects[index]!.id, project_objective_id:null }))
export const sampleSessions = ['Mix review','Vocal session','Team sync'].map((client_name,index) => ({id:`sample-session-${index}`, project_id:sampleProjects[index]!.id, client_name, session_date:today, start_time:['10:00:00','12:30:00','15:00:00'][index], end_time:['11:00:00','14:00:00','16:00:00'][index], session_type:['mixing','recording','meeting'][index], status:'confirmed', room:['Studio A','Studio B','Creative room'][index], notes:null, created_by:'dev-user', assigned_to:sampleMembers[index]!.id, google_event_id:null, google_sync_status:'synced', created_at:stamp}))
const channels = ['Mix review','Session planning','Announcements'].map((name,index) => ({ id:`sample-channel-${index}`, name, slug:`sample-${index}`, description:'', kind:'public', pinned_at:null, created_at:stamp }))
export const sampleMessages = channels.flatMap(channel => ['The latest mix is ready for review.', 'I’ll check the vocal balance before the session.', 'Session files are organized and ready.'].map((content,index) => ({ id:`${channel.id}-message-${index}`, channel_id:channel.id, sender_name:sampleMembers[index]!.display_name, sender_id:sampleMembers[index]!.id, sender_initial:sampleMembers[index]!.display_name.charAt(0), content, created_at:new Date(now.getTime()-(3-index)*600000).toISOString(), attachments:[], edited_at:null })))
export const sampleTables: Record<string, Record<string, unknown>[]> = {
  team_members:sampleMembers, projects:sampleProjects, assigned_tasks:sampleTasks, sessions:sampleSessions, chat_channels:channels, chat_messages:sampleMessages,
  media_submissions: ['EchoesInGold_Mix04.wav','StudioSession_CamA.mp4','AfterHours_Cover03.png','Northline_VocalComp.aiff','Master_Print_v2.wav','Mix_Notes_Round04.pdf'].map((original_filename,index) => ({id:`sample-media-${index}`, member_id:'dev-user', drive_file_id:`sample-file-${index}`, drive_view_url:null, original_filename, stored_filename:original_filename, size_bytes:(index+1)*1024*1024, content_type:['audio/wav','video/mp4','image/png','audio/aiff','audio/wav','application/pdf'][index], created_at:stamp, submitter:{display_name:sampleMembers[index%sampleMembers.length]!.display_name}})),
}
export const sampleThreads = sampleMembers.slice(1,3).map((member,index) => ({channel_id:`sample-dm-${index}`,kind:'dm',title:null,members:[{id:member.id,display_name:member.display_name,avatar_url:null}],unread_count:0,latest_id:`sample-dm-message-${index}`,latest_content:['The session files are ready.','Thursday works for me.'][index],latest_sender:member.display_name,latest_created_at:stamp,last_read_at:stamp}))
for (const thread of sampleThreads) {
  sampleTables.chat_messages!.push({id:thread.latest_id,channel_id:thread.channel_id,sender_name:thread.latest_sender,sender_id:thread.members[0]!.id,sender_initial:thread.latest_sender.charAt(0),content:thread.latest_content,created_at:stamp,attachments:[],edited_at:null})
}

Object.assign(sampleTables.media_submissions![0]!, { drive_view_url: sampleAudio, size_bytes: 16044 })
Object.assign(sampleTables.media_submissions![2]!, { original_filename: 'AfterHours_Cover03.svg', content_type: 'image/svg+xml', drive_view_url: sampleArtwork, size_bytes: 706 })
sampleTables.project_objectives = sampleProjects.flatMap((project,index) => ['Prepare','Review','Deliver'].map((title,step) => ({id:`${project.id}-objective-${step}`,project_id:project.id,title,sort_order:step,is_completed:step<index+1,completed_at:step<index+1?stamp:null,created_at:stamp})))
