-- Sessions polish #1 — recurring delete with scope.
--
-- The existing `admin_delete_session(p_session_id, p_cancel_note)`
-- handles single-row deletes. Per user direction on Calendar polish:
-- when an admin deletes a RECURRING booking, the UI should ask
-- "this event only" vs "this and all future events?" — Google
-- Calendar style. The first option already works via
-- `admin_delete_session`; this migration adds the second.
--
-- Recurring sessions model (recap):
--   - Template row: has `recurrence_spec` jsonb NOT NULL, no
--     `recurrence_parent_id`. Created by the admin via
--     `CreateBookingModal` when they pick weekly/monthly.
--   - Child rows: `recurrence_parent_id` points at the template,
--     `recurrence_spec` is NULL. Generated by the cron
--     `spawn_recurring_session_instances()` rolling 4–5 weeks
--     ahead.
--
-- "This and future" semantics:
--   1. Resolve the template_id: self if the clicked row IS the
--      template, else its recurrence_parent_id.
--   2. Pick the starting date: the clicked row's session_date.
--   3. Delete every row in the series (id = template OR
--      recurrence_parent_id = template) where session_date >=
--      starting_date.
--   4. ALSO null out the template's recurrence_spec so tomorrow's
--      cron doesn't spawn fresh children of a dead series. (No-op
--      if the template itself was just deleted.)
--   5. Return google_event_ids of every deleted row so the client
--      can sweep them out of Google Calendar.

CREATE OR REPLACE FUNCTION public.admin_delete_future_sessions(
  p_session_id uuid,
  p_cancel_note text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_caller        uuid := auth.uid();
  v_team          uuid := public.get_my_team_id();
  v_session       public.sessions%ROWTYPE;
  v_template_id   uuid;
  v_starting_date date;
  v_google_ids    text[];
  v_deleted_count int;
BEGIN
  IF v_caller IS NULL OR NOT public.is_team_admin() THEN
    RAISE EXCEPTION 'forbidden' USING ERRCODE = '42501';
  END IF;

  -- Team-scoped lookup. A cross-team uuid returns NULL → "not found"
  -- instead of leaking that the row exists elsewhere.
  SELECT * INTO v_session FROM public.sessions
   WHERE id = p_session_id AND team_id = v_team;
  IF v_session.id IS NULL THEN
    RAISE EXCEPTION 'session not found' USING ERRCODE = 'P0002';
  END IF;

  -- Resolve the template: self when this row IS the template, else
  -- its recurrence_parent_id. NULL when the row isn't part of any
  -- series (in which case we degenerate to a single-row delete).
  IF v_session.recurrence_spec IS NOT NULL THEN
    v_template_id := v_session.id;
  ELSE
    v_template_id := v_session.recurrence_parent_id;
  END IF;
  v_starting_date := v_session.session_date;

  IF v_template_id IS NULL THEN
    -- Not recurring — collect google_event_id + delete just this one.
    -- (Callers should usually use admin_delete_session for this case,
    -- but supporting the degenerate path here means the client can
    -- always call this function without sniffing the recurrence
    -- shape first.)
    SELECT ARRAY[v_session.google_event_id] INTO v_google_ids
      WHERE v_session.google_event_id IS NOT NULL;
    DELETE FROM public.sessions
      WHERE id = p_session_id AND team_id = v_team;
    GET DIAGNOSTICS v_deleted_count = ROW_COUNT;
  ELSE
    -- Recurring — collect google_event_ids for every row we're about
    -- to delete (template if applicable + all child rows with
    -- session_date >= starting_date). Stripped of NULLs so the
    -- client doesn't have to filter.
    SELECT ARRAY(
      SELECT google_event_id FROM public.sessions
       WHERE (id = v_template_id OR recurrence_parent_id = v_template_id)
         AND session_date >= v_starting_date
         AND team_id = v_team
         AND google_event_id IS NOT NULL
    ) INTO v_google_ids;

    -- Stop the cron from spawning fresh children of this dead series.
    -- Safe no-op if the template's session_date is also >= starting_date
    -- (it'll get deleted in the next statement). Touching it
    -- explicitly avoids a race with `spawn_recurring_session_instances()`
    -- between the DELETE and the next cron tick.
    UPDATE public.sessions SET recurrence_spec = NULL
     WHERE id = v_template_id AND team_id = v_team;

    -- Delete this + every future sibling in the series.
    DELETE FROM public.sessions
     WHERE (id = v_template_id OR recurrence_parent_id = v_template_id)
       AND session_date >= v_starting_date
       AND team_id = v_team;
    GET DIAGNOSTICS v_deleted_count = ROW_COUNT;
  END IF;

  RETURN jsonb_build_object(
    'deleted_count', v_deleted_count,
    'deleted_google_event_ids', COALESCE(v_google_ids, ARRAY[]::text[]),
    'cancel_note', p_cancel_note
  );
END;
$$;

GRANT EXECUTE ON FUNCTION public.admin_delete_future_sessions(uuid, text) TO authenticated;

COMMENT ON FUNCTION public.admin_delete_future_sessions IS
  'Delete a session + all FUTURE siblings in its recurring series. Returns deleted_count + deleted_google_event_ids so the client can sweep Google Calendar. Use admin_delete_session for single-row deletes (or call this on a non-recurring row — it degenerates safely).';
